### ISSUE TITLE
github.com/trezor/usbhid is no longer exists

### ISSUE THREAD

**Issue by xaionaro** [conejoninja/tesoro#13]
https://github.com/conejoninja/tesoro/blob/master/transport/webusb.go#L12

It causes problems with `dep ensure`. An example: https://github.com/xaionaro-go/cryptoWallet/issues/3

**Comment by conejoninja** [comment]
Thanks!
Looks like trezor/usbhid has beend moved to trezor/trezord-go/usb/lowlevel

https://github.com/trezor/trezord-go/commit/cc90c6fe8656b4e80bfa5e19925d697aa0102677

trezor/usbhid is vendored, but I leave this issue open to replace it in the future

**Comment by xaionaro** [comment]
A comment from a developer of `trezord-go`:
> I have moved usbhid here because it started to be too tightly coupled "logically" with this repo anyway :)
