### ISSUE TITLE
Error during build - cannot find "google/protobuf"

### ISSUE THREAD

**Issue by mattdf** [conejoninja/tesoro#4]
In `pb/types/types.pb.go` the reference to `google/protobuf` import cannot be resolved. 

Even if I change the import to `github.com/codejoninja/tesoro/pb/google/protobuf`, it then complains about a non-local import error in `messages.pb.go` for the `types` import.

**Comment by conejoninja** [comment]
I had (some of) the files updated on my machine, but not on the latest commit. It should be working now, please let me know if it works for you. 

The proto files were not updated in some time (same goes to https://github.com/conejoninja/cerrojo )
